const sizes = {
  XS: 'xs',
  S: 's',
  M: 'm',
  L: 'l',
  XL: 'xl',
};

const products = [
  {
    id: 1,
    image: `${process.env.CYCLIC_URL}/product1.png`,
    name: 'Jacket CLR Black',
    collection: 'Fable of Klassik',
    categoryId: 1,
    size: sizes.L,
    color: 'black',
    price: 710,
  },
  {
    id: 2,
    heroImage: `${process.env.CYCLIC_URL}/product-hero2.png`,
    image: `${process.env.CYCLIC_URL}/product2.png`,
    name: 'Jacket CLR Blue',
    collection: 'Fable of Klassik',
    categoryId: 1,
    size: sizes.L,
    color: 'blue',
    price: 550,
  },
  {
    id: 3,
    image: `${process.env.CYCLIC_URL}/product3.png`,
    name: 'Jacket CLR Ruby',
    collection: 'Fable of Klassik',
    categoryId: 1,
    size: sizes.L,
    color: 'ruby',
    price: 800,
  },
  {
    id: 4,
    heroImage: `${process.env.CYCLIC_URL}/product-hero4.png`,
    image: `${process.env.CYCLIC_URL}/product4.png`,
    name: 'Jacket CLR White',
    collection: 'Fable of Klassik',
    categoryId: 1,
    size: sizes.L,
    color: 'white',
    price: 920,
  },
  {
    id: 5,
    image: `${process.env.CYCLIC_URL}/product5.png`,
    name: 'Jacket CLR Green',
    collection: 'Fable of Klassik',
    categoryId: 1,
    size: sizes.S,
    color: 'green',
    price: 929,
  },
  {
    id: 6,
    heroImage: `${process.env.CYCLIC_URL}/product-hero6.png`,
    image: `${process.env.CYCLIC_URL}/product6.png`,
    name: 'Jacket CLR Orange',
    collection: 'Fable of Klassik',
    categoryId: 1,
    size: sizes.L,
    color: 'orange',
    price: 420,
  },
  {
    id: 7,
    image: `${process.env.CYCLIC_URL}/product7.png`,
    name: 'Shorts CLR Blue',
    collection: 'Fable of Klassik',
    categoryId: 2,
    size: sizes.L,
    color: 'blue',
    price: 470,
  },
  {
    id: 8,
    heroImage: `${process.env.CYCLIC_URL}/product-hero8.png`,
    image: `${process.env.CYCLIC_URL}/product8.png`,
    name: 'Shorts CLR Black',
    collection: 'Fable of Klassik',
    categoryId: 2,
    size: sizes.L,
    color: 'black',
    price: 570,
  },
  {
    id: 9,
    image: `${process.env.CYCLIC_URL}/product9.png`,
    name: 'Shorts CLR White',
    collection: 'Fable of Klassik',
    categoryId: 2,
    size: sizes.L,
    color: 'white',
    price: 1120,
  },
  {
    id: 10,
    image: `${process.env.CYCLIC_URL}/product10.png`,
    name: 'Shorts CLR Orange',
    collection: 'Fable of Klassik',
    categoryId: 2,
    size: sizes.L,
    color: 'orange',
    price: 875,
  },
  {
    id: 11,
    image: `${process.env.CYCLIC_URL}/product11.png`,
    name: 'Shorts CLR Ruby',
    collection: 'Fable of Klassik',
    categoryId: 2,
    size: sizes.XL,
    color: 'ruby',
    price: 835,
  },
];

const heroProducts = [
  products.find((p) => p.id == 2),
  { id: null, heroImage: `${process.env.CYCLIC_URL}/product-hero-a.png` },
  products.find((p) => p.id == 6),
  { id: null, heroImage: `${process.env.CYCLIC_URL}/product-hero-b.png` },
  products.find((p) => p.id == 8),
  products.find((p) => p.id == 4),
  { id: null, heroImage: `${process.env.CYCLIC_URL}/product-hero-c.png` },
  { id: null, heroImage: `${process.env.CYCLIC_URL}/product-hero-d.png` },
  { id: null, heroImage: `${process.env.CYCLIC_URL}/product-hero-e.png` },
];

module.exports = { products, heroProducts };
